### ISSUE TITLE
Current Python requirement / known to work

### ISSUE THREAD

**Issue by JFlin5** [bots-edi/bots#1]
What is the current Target Python version?
What is the minimum?

e.g. Minimum version tried is 3.0.0 (seems to work, and ideally is tested against this min)
Target Version is 3.1.2 (e.g. It better work with this one)
Last Tried is 3.4.5 (Might work with a later version of this, but until target / accepted, use at own risk)
(ALL fake versions)

**Comment by lw-schick** [comment]
Actually, I don't know. I guess it is still python 2.6 or 2.7 (as written in the [Documentation](https://github.com/skilchen/bots/wiki/StartInstallWindows)).

In [my repo](https://github.com/lw-schick/bots) I made some changes to run it on python 3.4.3 and django 1.9.6. - but that should'nt be used for production environments. There might be still bugs f.e. https://github.com/lw-schick/bots/issues/5

**Comment by JFlin5** [comment]
Would suggest that a Target be set for this branch (3.4.3 seems fine to me), and that the definition of "works" be that it passes a master test suite, then once get the Target branch going, can try backward/forward to determine Min/Max at some point

Gives people an idea of what should be tried, and eventually tests that are failing, to eventually get fully usable as a release

If get working in 3.4.3, and still works fine in 2.7, then could also suggest it being re-merged into the "Master" version rather than maintaining a branch

**Comment by lw-schick** [comment]
Actually, thats the plan. The thing is that we currently have no maintainer for the "Master" version...

**Comment by WouterVH** [comment]
For python 2, we should target python 2.7.
For python, target python 3.4 and up.

drop support for older versions

**Comment by WouterVH** [comment]
@lw-schick can you make a pull request to support the latest django?

**Comment by WouterVH** [comment]
is anyone running bots on python3?

**Comment by lw-schick** [comment]
@WouterVH See PR https://github.com/bots-edi/bots/pull/10

**Comment by lw-schick** [comment]
@WouterVH My branch runs on python 3.4.3 and I have no problems with that. Maybe you should just test it...?

**Comment by WouterVH** [comment]
we should support python 2.7 and python3.4+, and fix any issues with those

issues reported python for python 2.5, 2.6, 3.0, 3.1, 3.2, 3.3 are wontfix.

**Comment by WouterVH** [comment]
in setup.py? I added  python 2.7 and python3.4, 3.5 as supported versions.
I also added an image that will display this in the readme (visible after publishing on pypi)
