### ISSUE TITLE
Rename repo to "bots"

### ISSUE THREAD

**Issue by JCapriotti** [bots-edi/bots#3]
Though there hasn't been a lot of activity here, there is potential for this to be a mature fork. 

Does anyone mind if we rename this repo to just be "bots". Having "tmp" has a bad connotation.

**Comment by lw-schick** [comment]
I think that's a good idea!

**Comment by WouterVH** [comment]
Do you believe it's OK to fork a project and keep the same name?

**Comment by WouterVH** [comment]
bots-tmp renamed back to bots.
further discussion in #7
