### ISSUE TITLE
NameError: global name 'ta_info' is not defined

### ISSUE THREAD

**Issue by stevenmwade** [bots-edi/bots#39]
I do not have `ta_info` in my code and only use it on the `inn` and `out` passed into the function. Bots does not give a line number in which file so there is no way of actually finding where this error is occurring.

This is the detail:
`Merged	Error | 11	| 1 | x12 | 850005010 | steven_test_json_in | FGFan Groups228 | NameError: global name 'ta_info' is not defined | us-ascii | application/X12`

**Comment by djfurman** [comment]
Hi @stevenmwade,

In your bots/config/bots.ini you can set your debug levels to `DEBUG` for the logs so you can see what levels specifically are affected.

Can you post your imports at the top of your mapping script? From what you posted I'm assuming that you're translating a 5010 X12 PO to custom JSON structure; to make `ta_info` available to your mapping script you need to be importing it.

**Comment by stevenmwade** [comment]
Found the debugs and finally found the problem in the grammar.
