### ISSUE TITLE
Gitter Join Chat

### ISSUE THREAD

**Issue by lw-schick** [bots-edi/bots#5]
Can we add a gitter join chat button in the README?

Look here for an example: https://github.com/gitter-badger/ark

**Comment by JCapriotti** [comment]
Added in #9 

I found out I don't have access to commit, so it is in a fork with PR.

FWIW, even if I had commit access, I tend to favor branches and PRs over direct commits for code changes. Reviews are good :)

**Comment by WouterVH** [comment]
Merged.
