### ISSUE TITLE
New Project Name

### ISSUE THREAD

**Issue by JCapriotti** [bots-edi/bots#7]
So if this is truly a fork, it should have a new project name. Thoughts?

**Comment by WouterVH** [comment]
I tried to contact HenkJan via ways ways:
none of my 5 emails to the botsmailinglist got through.
I've send several messages to his personal email, none of which got answered.

@JCapriotti I propose that you start a discussion on the bots-mailinglist.
My strong preference is to avoid a fork and renaming of the project, and that bots-edi/bots becomes the official repository.

**Comment by WouterVH** [comment]
If HenkJan does not complain, let's keep the original name.
Reopen when needed.

**Comment by WouterVH** [comment]
if we need a new name, one simple idea is to call it ",bots-edi"

**Comment by JCapriotti** [comment]
I was thinking a new name more to prevent confusion when people are looking for documentation, help, etc. Though, I guess it could create more confusion, initially. But bots-edi might be a good way to distinguish this.
